### ISSUE TITLE
Incorrect tab highlighted

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/next-front-page#232] opened 2015-09-01 09:30 UTC
Front page mobile bug. Click on fastft tab, click on fastft article, go back - incorrect tab is highlighted

![image](https://cloud.githubusercontent.com/assets/447559/9600690/619fd350-5094-11e5-8059-cdde3e4e4c25.png)

**Comment by charypar** [comment] 2015-09-01 11:11
Cannot reproduce on iPhone, only in Chrome.

**Comment by wheresrhys** [comment] 2015-09-02 11:46
Fastft tab now missing from mobile. Is this a feature or bug?

**Comment by imranolas** [comment] 2015-09-02 13:02
It's a bug #236

**Comment by SelinaBans1** [comment] 2015-09-24 07:55
@charypar  i think this is fixed now - happy to close it?

**Closed** 2015-09-25 11:32 UTC
Labels: bug
